from docurapi.db.connection import connect, initialize_database, utc_now
from docurapi.db.jobs_repository import (
    clear_job_history,
    complete_job,
    create_job,
    delete_job,
    fail_job,
    get_job,
    list_jobs,
    mark_job_paid,
    remove_job_files,
)
from docurapi.db.payments_repository import (
    create_payment_record,
    get_latest_payment_for_job,
    get_payment,
    list_payments_for_job,
    mark_latest_payment_paid_for_job,
    mark_payment_failed,
    mark_payment_paid,
)
from docurapi.db.templates_repository import (
    delete_template,
    get_template,
    list_templates,
    register_template,
    remove_template_file,
)

__all__ = [
    "connect",
    "initialize_database",
    "utc_now",
    "create_job",
    "complete_job",
    "fail_job",
    "mark_job_paid",
    "get_job",
    "list_jobs",
    "delete_job",
    "clear_job_history",
    "remove_job_files",
    "create_payment_record",
    "get_latest_payment_for_job",
    "get_payment",
    "list_payments_for_job",
    "mark_latest_payment_paid_for_job",
    "mark_payment_failed",
    "mark_payment_paid",
    "register_template",
    "list_templates",
    "get_template",
    "delete_template",
    "remove_template_file",
]
